/**
 * CATÁLOGO DE PLANTILLAS · BORRADOR PARA REVISIÓN LEGAL
 *
 * ⚠️  Todas se cargan con status = 'DRAFT'. No son visibles para los
 *     usuarios hasta que un abogado dominicano las revise y publique.
 *
 * Cada entrada compone el documento a partir de cláusulas de la
 * biblioteca. El texto legal vive en las cláusulas, no aquí: revisar
 * una cláusula mejora todas las plantillas que la usan.
 *
 * Formato: [categoría, título, descripción, cláusulas específicas]
 * A todas se les añaden automáticamente las cláusulas de cierre
 * (notificaciones, ley aplicable, modificaciones, divisibilidad, firmas).
 */

export type TemplateSeed = [
  category: string,
  title: string,
  description: string,
  clauses: string[],
]

/** Cláusulas de cierre que lleva todo contrato. */
export const CIERRE = [
  'g-declaraciones-partes',
  'g-modificaciones',
  'g-divisibilidad',
  'g-notificaciones',
  'g-ley-aplicable',
  'integridad-contractual',
]

/** Bloques reutilizables para no repetir listas largas. */
export const BLOQUE = {
  economico: ['e-precio-servicios', 'e-forma-pago', 'e-impuestos-retenciones', 'e-facturacion'],
  confidencial: ['b-confidencialidad', 'b-propiedad-intelectual'],
  laboralBase: ['l-salario', 'l-jornada', 'l-vacaciones', 'l-confidencialidad', 'l-terminacion-laboral', 'l-periodo-prueba'],
  tecnologiaBase: ['t-soporte-tecnico', 't-nivel-servicio', 't-seguridad-informacion', 't-proteccion-datos'],
  obraBase: ['o-plazo-obra', 'o-materiales', 'o-recepcion-obra', 'e-retencion-garantia'],
  arrendamiento: ['g-objeto-uso-bien', 'e-precio-alquiler', 'deposito-garantia', 'mora-recargo', 'vigencia-arrendamiento', 'terminacion-anticipada', 'i-entrega-inmueble', 'g-devolucion-bien', 'reparaciones-menores', 'incumplimiento-desalojo'],
}

export const TEMPLATES: TemplateSeed[] = [

/* ══════════ INMOBILIARIO (35) ══════════ */
['inmobiliario', 'Contrato de Alquiler de Local Comercial', 'Arrendamiento de local para actividad comercial, con uso comercial y reglamento de condominio.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-reglamento-condominio', 'i-servicios-excluidos', 'remodelaciones', 'subarrendamiento-prohibido']],
['inmobiliario', 'Contrato de Alquiler de Apartamento Amueblado', 'Arrendamiento de apartamento con mobiliario, inventario anexo y depósito reforzado.', [...BLOQUE.arrendamiento, 'uso-residencial', 'inventario-mobiliario', 'i-areas-comunes', 'i-reglamento-condominio', 'servicios-incluidos']],
['inmobiliario', 'Contrato de Alquiler de Habitación', 'Arrendamiento de habitación en vivienda compartida.', [...BLOQUE.arrendamiento, 'uso-residencial', 'i-areas-comunes', 'i-servicios-excluidos', 'subarrendamiento-prohibido']],
['inmobiliario', 'Contrato de Alquiler Vacacional', 'Arrendamiento de corta estancia para uso turístico.', ['objeto-arrendamiento', 'precio-renta', 'deposito-garantia', 'i-entrega-inmueble', 'inventario-mobiliario', 'devolucion-inmueble', 'i-reglamento-condominio']],
['inmobiliario', 'Contrato de Alquiler de Villa', 'Arrendamiento de villa residencial con áreas y servicios propios.', [...BLOQUE.arrendamiento, 'uso-residencial', 'inventario-mobiliario', 'mantenimiento-arrendador', 'estacionamiento', 'i-seguro-inmueble']],
['inmobiliario', 'Contrato de Alquiler de Oficina', 'Arrendamiento de espacio de oficina en edificio corporativo.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-areas-comunes', 'i-reglamento-condominio', 'estacionamiento']],
['inmobiliario', 'Contrato de Alquiler de Nave Industrial', 'Arrendamiento de nave o almacén para uso industrial o logístico.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-seguro-inmueble', 'remodelaciones', 'i-servicios-excluidos']],
['inmobiliario', 'Contrato de Alquiler de Terreno', 'Arrendamiento de solar o parcela sin edificación.', ['objeto-arrendamiento', 'i-descripcion-inmueble', 'precio-renta', 'vigencia-arrendamiento', 'remodelaciones', 'devolucion-inmueble']],
['inmobiliario', 'Contrato de Alquiler de Parqueo', 'Arrendamiento de espacio de estacionamiento.', ['objeto-arrendamiento', 'precio-renta', 'vigencia-arrendamiento', 'estacionamiento', 'i-reglamento-condominio']],
['inmobiliario', 'Contrato de Compraventa de Inmueble', 'Venta de inmueble con transferencia ante Registro de Títulos.', ['c-objeto-compraventa', 'i-descripcion-inmueble', 'i-garantia-saneamiento', 'i-transferencia-propiedad', 'e-forma-pago', 'c-entrega-bien']],
['inmobiliario', 'Promesa de Venta de Inmueble', 'Compromiso de venta futura con arras y plazo para formalizar.', ['i-descripcion-inmueble', 'e-pago-anticipado', 'i-garantia-saneamiento', 'i-transferencia-propiedad', 'g-penalidad']],
['inmobiliario', 'Contrato de Opción de Compra', 'Derecho de compra dentro de un plazo determinado.', ['i-descripcion-inmueble', 'e-pago-anticipado', 'i-garantia-saneamiento', 'g-penalidad']],
['inmobiliario', 'Contrato de Corretaje Inmobiliario', 'Intermediación en la venta o alquiler de un inmueble.', ['b-exclusividad', 'e-comision-porcentaje', 'b-territorio', 'g-renovacion-automatica']],
['inmobiliario', 'Contrato de Administración de Inmuebles', 'Gestión de uno o varios inmuebles por cuenta del propietario.', ['e-comision-porcentaje', 'b-representacion', 'e-reembolso-gastos', 'g-renovacion-automatica', 'b-relacion-independiente']],
['inmobiliario', 'Contrato de Permuta de Inmuebles', 'Intercambio de inmuebles entre dos partes.', ['i-descripcion-inmueble', 'i-garantia-saneamiento', 'i-transferencia-propiedad', 'c-entrega-bien']],
['inmobiliario', 'Contrato de Arrendamiento con Opción a Compra', 'Alquiler que permite adquirir el inmueble al final del plazo.', [...BLOQUE.arrendamiento, 'i-descripcion-inmueble', 'i-transferencia-propiedad', 'e-pago-anticipado']],
['inmobiliario', 'Contrato de Subarrendamiento', 'Cesión parcial o total del uso por parte del arrendatario.', ['objeto-arrendamiento', 'subarrendamiento-permitido', 'precio-renta', 'vigencia-arrendamiento', 'devolucion-inmueble']],
['inmobiliario', 'Acta de Entrega de Inmueble', 'Constancia del estado del inmueble al entregarlo.', ['i-entrega-inmueble', 'inventario-mobiliario', 'i-inspeccion-periodica']],
['inmobiliario', 'Acta de Devolución de Inmueble', 'Constancia del estado al finalizar el arrendamiento.', ['devolucion-inmueble', 'i-pintura-conservacion', 'deposito-garantia']],
['inmobiliario', 'Recibo de Depósito de Garantía', 'Comprobante de entrega del depósito.', ['deposito-garantia']],
['inmobiliario', 'Carta de Desalojo', 'Requerimiento formal de desocupación del inmueble.', ['incumplimiento-desalojo', 'devolucion-inmueble', 'g-notificaciones']],
['inmobiliario', 'Notificación de No Renovación', 'Aviso de que el contrato no se prorrogará.', ['g-renovacion-automatica', 'devolucion-inmueble', 'g-notificaciones']],
['inmobiliario', 'Notificación de Aumento de Renta', 'Comunicación del ajuste del precio del alquiler.', ['e-ajuste-precio-anual', 'g-notificaciones']],
['inmobiliario', 'Contrato de Mantenimiento de Inmueble', 'Servicio periódico de mantenimiento de una propiedad.', ['mantenimiento-arrendador', 'e-precio-servicios', 'e-forma-pago', 'g-renovacion-automatica']],
['inmobiliario', 'Reglamento Interno de Condominio', 'Normas de convivencia y uso de áreas comunes.', ['i-reglamento-condominio', 'i-areas-comunes', 'estacionamiento', 'mascotas']],
['inmobiliario', 'Contrato de Alquiler de Local en Plaza Comercial', 'Arrendamiento en centro comercial con horario y reglamento común.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-reglamento-condominio', 'i-areas-comunes', 'e-ajuste-precio-anual']],
['inmobiliario', 'Contrato de Alquiler de Consultorio', 'Arrendamiento de espacio para consulta profesional.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-areas-comunes', 'servicios-incluidos']],
['inmobiliario', 'Contrato de Alquiler de Bodega', 'Arrendamiento de espacio de almacenamiento.', [...BLOQUE.arrendamiento, 'uso-comercial', 'i-seguro-inmueble', 'i-servicios-excluidos']],
['inmobiliario', 'Contrato de Alquiler de Equipo de Construcción', 'Arrendamiento de maquinaria para obra.', ['objeto-arrendamiento', 'precio-renta', 'i-entrega-inmueble', 'e-deposito-general', 'g-penalidad']],
['inmobiliario', 'Contrato de Usufructo', 'Derecho de uso y disfrute sobre un inmueble ajeno.', ['i-descripcion-inmueble', 'vigencia-arrendamiento', 'reparaciones-menores', 'devolucion-inmueble']],
['inmobiliario', 'Contrato de Comodato de Inmueble', 'Préstamo gratuito de uso de un inmueble.', ['objeto-arrendamiento', 'vigencia-arrendamiento', 'reparaciones-menores', 'devolucion-inmueble']],
['inmobiliario', 'Declaración Jurada de Ocupación', 'Declaración sobre quién ocupa el inmueble.', ['i-descripcion-inmueble', 'g-declaraciones-partes']],
['inmobiliario', 'Contrato de Servidumbre de Paso', 'Constitución de derecho de paso sobre un predio.', ['i-descripcion-inmueble', 'i-transferencia-propiedad', 'g-obligaciones-partes']],
['inmobiliario', 'Contrato de Hipoteca', 'Garantía real sobre inmueble en respaldo de una deuda.', ['i-descripcion-inmueble', 'p-capital-prestamo', 'p-garantia-prestamo', 'p-amortizacion', 'g-intereses-moratorios']],
['inmobiliario', 'Contrato de Alquiler de Espacio para Evento', 'Cesión temporal de un espacio para un evento puntual.', ['objeto-arrendamiento', 'precio-renta', 'e-deposito-general', 'i-entrega-inmueble', 'g-penalidad']],

/* ══════════ LEGAL / GENERAL (25) ══════════ */
['legal-general', 'Poder General', 'Mandato amplio para actuar en nombre del poderdante.', ['b-representacion', 'g-declaraciones-partes', 'g-terminacion-mutuo-acuerdo']],
['legal-general', 'Poder Especial', 'Mandato limitado a un acto concreto.', ['b-representacion', 'g-declaraciones-partes', 'vigencia-arrendamiento']],
['legal-general', 'Poder para Trámites ante la DGII', 'Representación ante Impuestos Internos.', ['b-representacion', 'g-declaraciones-partes']],
['legal-general', 'Revocación de Poder', 'Deja sin efecto un mandato otorgado.', ['b-representacion', 'g-notificaciones']],
['legal-general', 'Acuerdo de Confidencialidad (NDA)', 'Protección de información sensible entre las partes.', ['b-confidencialidad', 'b-propiedad-intelectual', 'g-penalidad', 'g-arbitraje']],
['legal-general', 'Acuerdo de Confidencialidad Mutuo', 'Ambas partes intercambian y protegen información.', ['b-confidencialidad', 'g-penalidad', 'g-solucion-controversias']],
['legal-general', 'Acuerdo de Transacción', 'Pone fin a una controversia mediante concesiones mutuas.', ['g-terminacion-mutuo-acuerdo', 'e-forma-pago', 'g-penalidad', 'b-confidencialidad']],
['legal-general', 'Contrato de Mediación', 'Designación de un mediador para resolver un conflicto.', ['g-mediacion-previa', 'e-precio-servicios', 'b-confidencialidad']],
['legal-general', 'Convenio de Arbitraje', 'Somete las controversias a un tribunal arbitral.', ['g-arbitraje', 'g-solucion-controversias']],
['legal-general', 'Carta de Intención', 'Manifestación de voluntad previa a un contrato definitivo.', ['g-declaraciones-partes', 'b-confidencialidad', 'g-buena-fe']],
['legal-general', 'Acuerdo de Exclusividad de Negociación', 'Compromiso de no negociar con terceros por un plazo.', ['b-exclusividad', 'b-confidencialidad', 'g-penalidad']],
['legal-general', 'Declaración Jurada', 'Declaración formal bajo fe de juramento.', ['g-declaraciones-partes']],
['legal-general', 'Acto de Notoriedad', 'Constancia notarial de hechos conocidos.', ['g-declaraciones-partes']],
['legal-general', 'Contrato de Cesión de Derechos', 'Transferencia de derechos a un tercero.', ['g-cesion-permitida', 'e-precio-servicios', 'g-declaraciones-partes']],
['legal-general', 'Contrato de Cesión de Crédito', 'Traspaso de un crédito a un nuevo acreedor.', ['g-cesion-permitida', 'g-notificaciones', 'g-declaraciones-partes']],
['legal-general', 'Reconocimiento de Deuda', 'El deudor reconoce lo que debe y cómo pagará.', ['p-capital-prestamo', 'p-amortizacion', 'g-intereses-moratorios', 'g-penalidad']],
['legal-general', 'Finiquito', 'Declaración de que no queda nada pendiente entre las partes.', ['g-terminacion-mutuo-acuerdo', 'g-declaraciones-partes']],
['legal-general', 'Carta de Renuncia a Reclamación', 'Renuncia expresa a ejercer una acción.', ['g-declaraciones-partes', 'g-terminacion-mutuo-acuerdo']],
['legal-general', 'Contrato de Depósito', 'Custodia de un bien por cuenta de otro.', ['e-deposito-general', 'c-entrega-bien', 'g-obligaciones-partes']],
['legal-general', 'Contrato de Fianza', 'Un tercero garantiza el cumplimiento de una obligación.', ['p-garantia-prestamo', 'g-obligaciones-partes', 'g-penalidad']],
['legal-general', 'Acuerdo de Terminación Anticipada', 'Poner fin a un contrato antes de su vencimiento.', ['g-terminacion-mutuo-acuerdo', 'e-reembolso-gastos', 'g-declaraciones-partes']],
['legal-general', 'Adenda Contractual', 'Modificación de un contrato ya firmado.', ['g-modificaciones', 'g-declaraciones-partes']],
['legal-general', 'Intimación de Pago', 'Requerimiento formal de pago de una deuda vencida.', ['g-intereses-moratorios', 'g-notificaciones', 'g-penalidad']],
['legal-general', 'Contrato de Prestación de Garantía', 'Constitución de garantía sobre bienes muebles.', ['p-garantia-prestamo', 'g-declaraciones-partes']],
['legal-general', 'Acuerdo de No Divulgación de Empleados', 'Confidencialidad exigida al personal.', ['l-confidencialidad', 'l-propiedad-intelectual', 'g-penalidad']],

/* ══════════ EMPRESARIAL / CORPORATIVO (30) ══════════ */
['empresarial', 'Contrato de Sociedad de Responsabilidad Limitada', 'Constitución de una SRL dominicana.', ['g-declaraciones-partes', 'g-obligaciones-partes', 'b-confidencialidad', 'g-arbitraje']],
['empresarial', 'Acuerdo de Socios', 'Reglas entre socios sobre gestión y salida.', ['g-cesion-prohibida', 'b-confidencialidad', 'b-no-competencia', 'g-arbitraje', 'g-solucion-controversias']],
['empresarial', 'Contrato de Compraventa de Acciones', 'Transferencia de participación societaria.', ['c-objeto-compraventa', 'g-declaraciones-partes', 'e-forma-pago', 'b-no-competencia']],
['empresarial', 'Contrato de Joint Venture', 'Alianza para un proyecto común.', ['b-relacion-independiente', 'b-confidencialidad', 'b-propiedad-intelectual', 'g-arbitraje']],
['empresarial', 'Contrato de Distribución', 'Distribución de productos en un territorio.', ['b-distribucion', 'b-territorio', 'b-exclusividad', 'e-comision-porcentaje', 'g-renovacion-automatica']],
['empresarial', 'Contrato de Distribución No Exclusiva', 'Distribución sin derechos exclusivos.', ['b-distribucion', 'b-no-exclusividad', 'b-territorio', 'e-forma-pago']],
['empresarial', 'Contrato de Representación Comercial', 'Actuación comercial en nombre de un tercero.', ['b-representacion', 'b-territorio', 'e-comision-porcentaje', 'b-relacion-independiente']],
['empresarial', 'Contrato de Agencia', 'Promoción de negocios por cuenta ajena.', ['b-representacion', 'e-comision-porcentaje', 'b-territorio', 'g-renovacion-automatica']],
['empresarial', 'Contrato de Franquicia', 'Cesión de marca y modelo de negocio.', ['b-exclusividad', 'b-territorio', 'b-propiedad-intelectual', 'e-comision-porcentaje', 'b-confidencialidad', 'b-no-competencia']],
['empresarial', 'Contrato de Suministro', 'Provisión periódica de bienes.', ['c-entrega-bien', 'e-precio-servicios', 'e-forma-pago', 'e-penalidad-retraso', 'g-renovacion-automatica']],
['empresarial', 'Contrato de Consignación', 'Entrega de mercancía para su venta por cuenta del proveedor.', ['c-entrega-bien', 'e-comision-porcentaje', 'g-obligaciones-partes']],
['empresarial', 'Contrato de Referidos Comerciales', 'Comisión por presentar clientes.', ['b-referidos', 'e-forma-pago', 'b-relacion-independiente']],
['empresarial', 'Acuerdo de Colaboración Empresarial', 'Cooperación entre empresas sin crear sociedad.', ['b-relacion-independiente', 'b-confidencialidad', 'b-propiedad-intelectual']],
['empresarial', 'Contrato de Licencia de Marca', 'Autorización para usar una marca registrada.', ['b-propiedad-intelectual', 'b-territorio', 'e-comision-porcentaje', 'b-exclusividad']],
['empresarial', 'Acta de Asamblea de Socios', 'Constancia de los acuerdos de la asamblea.', ['g-declaraciones-partes', 'g-encabezados']],
['empresarial', 'Acta de Consejo de Administración', 'Registro de decisiones del órgano de administración.', ['g-declaraciones-partes', 'g-encabezados']],
['empresarial', 'Contrato de Gerencia', 'Designación y condiciones de un gerente.', ['b-representacion', 'l-salario', 'b-confidencialidad', 'b-no-competencia', 'l-terminacion-laboral']],
['empresarial', 'Contrato de Consultoría Empresarial', 'Asesoría estratégica a una empresa.', ['e-precio-servicios', 'e-forma-pago', 'b-confidencialidad', 'b-relacion-independiente', 't-aceptacion-entregables']],
['empresarial', 'Contrato de Auditoría', 'Revisión independiente de estados financieros.', ['e-precio-servicios', 'b-confidencialidad', 'b-relacion-independiente', 't-aceptacion-entregables']],
['empresarial', 'Contrato de Outsourcing', 'Externalización de un proceso de negocio.', ['e-precio-servicios', 't-nivel-servicio', 'b-confidencialidad', 't-proteccion-datos', 'b-relacion-independiente']],
['empresarial', 'Contrato de Maquila', 'Fabricación por encargo.', ['c-entrega-bien', 'e-precio-servicios', 'e-penalidad-retraso', 'b-propiedad-intelectual', 'b-confidencialidad']],
['empresarial', 'Contrato de Logística y Transporte', 'Servicios de transporte y almacenaje de mercancía.', ['e-precio-servicios', 'c-entrega-bien', 'e-penalidad-retraso', 'g-seguro-bienes']],
['empresarial', 'Contrato de Corretaje Comercial', 'Intermediación en operaciones comerciales.', ['e-comision-porcentaje', 'b-relacion-independiente', 'b-territorio']],
['empresarial', 'Acuerdo de Nivel de Servicio Comercial', 'Compromisos de servicio entre empresas.', ['t-nivel-servicio', 't-disponibilidad', 'g-penalidad', 'e-precio-servicios']],
['empresarial', 'Contrato de Publicidad Corporativa', 'Contratación de espacios y campañas publicitarias.', ['e-precio-servicios', 'm-entregables-creativos', 'm-derechos-imagen', 'b-propiedad-intelectual']],
['empresarial', 'Contrato de Patrocinio', 'Aportación económica a cambio de exposición de marca.', ['e-precio-servicios', 'm-derechos-imagen', 'b-propiedad-intelectual', 'b-exclusividad']],
['empresarial', 'Contrato de Alianza Estratégica', 'Cooperación de largo plazo entre empresas.', ['b-relacion-independiente', 'b-exclusividad', 'b-confidencialidad', 'g-arbitraje']],
['empresarial', 'Contrato de Compra de Activos', 'Adquisición de activos de una empresa.', ['c-objeto-compraventa', 'g-declaraciones-partes', 'c-vicios-ocultos', 'e-forma-pago']],
['empresarial', 'Contrato de Cesión de Cartera de Clientes', 'Traspaso de una cartera comercial.', ['g-cesion-permitida', 'b-confidencialidad', 'b-no-competencia', 'e-forma-pago']],
['empresarial', 'Política de Cumplimiento Anticorrupción', 'Normas internas de integridad y prevención.', ['b-anticorrupcion', 'l-confidencialidad', 'g-obligaciones-partes']],

/* ══════════ LABORAL / RR. HH. (30) ══════════ */
['laboral', 'Contrato de Trabajo por Tiempo Indefinido', 'Relación laboral sin plazo determinado.', [...BLOQUE.laboralBase, 'l-equipos-trabajo', 'l-propiedad-intelectual']],
['laboral', 'Contrato de Trabajo por Tiempo Determinado', 'Relación laboral con fecha de término.', [...BLOQUE.laboralBase, 'vigencia-arrendamiento']],
['laboral', 'Contrato de Trabajo para Obra o Servicio', 'Contratación ligada a una obra concreta.', [...BLOQUE.laboralBase, 'o-plazo-obra']],
['laboral', 'Contrato de Trabajo a Tiempo Parcial', 'Jornada reducida respecto de la ordinaria.', [...BLOQUE.laboralBase]],
['laboral', 'Contrato de Trabajo Remoto', 'Prestación del servicio desde el domicilio.', [...BLOQUE.laboralBase, 'l-trabajo-remoto', 'l-equipos-trabajo']],
['laboral', 'Contrato de Trabajo Híbrido', 'Combinación de presencialidad y trabajo remoto.', [...BLOQUE.laboralBase, 'l-trabajo-hibrido', 'l-equipos-trabajo']],
['laboral', 'Contrato de Trabajo con Comisiones', 'Salario fijo más retribución variable por ventas.', [...BLOQUE.laboralBase, 'l-comision-ventas']],
['laboral', 'Contrato de Pasantía', 'Formación práctica de estudiante en la empresa.', ['l-jornada', 'l-confidencialidad', 'l-equipos-trabajo', 'vigencia-arrendamiento']],
['laboral', 'Contrato de Aprendizaje', 'Formación laboral con componente educativo.', ['l-jornada', 'l-salario', 'l-confidencialidad', 'vigencia-arrendamiento']],
['laboral', 'Contrato de Trabajo Doméstico', 'Servicio doméstico en hogar particular.', ['l-salario', 'l-jornada', 'l-vacaciones', 'l-terminacion-laboral']],
['laboral', 'Contrato de Trabajo de Alta Dirección', 'Personal directivo con funciones de confianza.', [...BLOQUE.laboralBase, 'b-no-competencia', 'l-propiedad-intelectual', 'b-representacion']],
['laboral', 'Carta de Oferta de Empleo', 'Propuesta formal de contratación.', ['l-salario', 'l-jornada', 'l-periodo-prueba']],
['laboral', 'Carta de Desahucio', 'Terminación del contrato por voluntad del empleador.', ['l-terminacion-laboral', 'g-notificaciones']],
['laboral', 'Carta de Despido por Falta Grave', 'Terminación por causa imputable al trabajador.', ['l-terminacion-laboral', 'g-notificaciones', 'g-declaraciones-partes']],
['laboral', 'Carta de Renuncia', 'Dimisión voluntaria del trabajador.', ['l-terminacion-laboral', 'l-equipos-trabajo', 'g-notificaciones']],
['laboral', 'Acuerdo de Terminación Laboral', 'Terminación por mutuo acuerdo con liquidación.', ['l-terminacion-laboral', 'g-terminacion-mutuo-acuerdo', 'l-confidencialidad']],
['laboral', 'Cálculo de Prestaciones Laborales', 'Liquidación de preaviso, cesantía y vacaciones.', ['l-terminacion-laboral', 'l-vacaciones', 'l-bonificacion']],
['laboral', 'Acuerdo de Confidencialidad Laboral', 'Reserva de información exigida al empleado.', ['l-confidencialidad', 'l-propiedad-intelectual', 'g-penalidad']],
['laboral', 'Acuerdo de No Competencia Laboral', 'Restricción de competir tras dejar la empresa.', ['b-no-competencia', 'l-confidencialidad', 'g-penalidad']],
['laboral', 'Contrato de Cesión de Derechos de Autor del Empleado', 'Titularidad de lo creado por el trabajador.', ['l-propiedad-intelectual', 'l-confidencialidad']],
['laboral', 'Acta de Entrega de Equipos', 'Constancia de las herramientas entregadas al empleado.', ['l-equipos-trabajo']],
['laboral', 'Política de Teletrabajo', 'Normas internas para el trabajo a distancia.', ['l-trabajo-remoto', 'l-equipos-trabajo', 'l-confidencialidad', 't-seguridad-informacion']],
['laboral', 'Reglamento Interno de Trabajo', 'Normas de conducta y disciplina en la empresa.', ['l-jornada', 'l-confidencialidad', 'l-terminacion-laboral', 'b-anticorrupcion']],
['laboral', 'Política de Vacaciones', 'Reglas de solicitud y disfrute de vacaciones.', ['l-vacaciones', 'l-jornada']],
['laboral', 'Amonestación Escrita', 'Llamado de atención formal al trabajador.', ['l-terminacion-laboral', 'g-notificaciones']],
['laboral', 'Contrato de Servicios Profesionales Independientes', 'Prestación sin relación laboral.', ['e-precio-servicios', 'b-relacion-independiente', 'b-confidencialidad', 'e-forma-pago']],
['laboral', 'Acuerdo de Bonificación por Desempeño', 'Retribución variable ligada a objetivos.', ['l-bonificacion', 'l-salario']],
['laboral', 'Contrato de Trabajo para Extranjeros', 'Relación laboral con trabajador no residente.', [...BLOQUE.laboralBase, 'g-declaraciones-partes']],
['laboral', 'Acuerdo de Reducción de Jornada', 'Modificación temporal del horario laboral.', ['l-jornada', 'l-salario', 'g-modificaciones']],
['laboral', 'Certificación Laboral', 'Constancia de la relación de trabajo.', ['g-declaraciones-partes']],

/* ══════════ SERVICIOS PROFESIONALES (30) ══════════ */
['servicios', 'Contrato de Servicios Profesionales', 'Prestación general de servicios por un profesional.', [...BLOQUE.economico, 'b-relacion-independiente', 'b-confidencialidad', 't-aceptacion-entregables']],
['servicios', 'Contrato de Servicios Legales', 'Asesoría y representación jurídica.', [...BLOQUE.economico, 'b-confidencialidad', 'b-representacion', 'b-relacion-independiente']],
['servicios', 'Contrato de Iguala Legal', 'Honorarios mensuales por asesoría continua.', ['e-precio-servicios', 'e-forma-pago', 'g-renovacion-automatica', 'b-confidencialidad']],
['servicios', 'Contrato de Servicios Contables', 'Llevanza de contabilidad y declaraciones fiscales.', [...BLOQUE.economico, 'b-confidencialidad', 'e-impuestos-retenciones']],
['servicios', 'Contrato de Auditoría Externa', 'Revisión independiente de cuentas.', [...BLOQUE.economico, 'b-confidencialidad', 't-aceptacion-entregables']],
['servicios', 'Contrato de Consultoría', 'Asesoría especializada por proyecto.', [...BLOQUE.economico, 'b-relacion-independiente', 't-aceptacion-entregables', 'b-propiedad-intelectual']],
['servicios', 'Contrato de Coaching Ejecutivo', 'Acompañamiento profesional individual.', ['e-precio-servicios', 'e-forma-pago', 'b-confidencialidad', 'b-relacion-independiente']],
['servicios', 'Contrato de Capacitación', 'Impartición de formación al personal.', [...BLOQUE.economico, 'm-entregables-creativos', 'b-propiedad-intelectual']],
['servicios', 'Contrato de Traducción', 'Traducción de documentos.', ['e-precio-servicios', 'e-forma-pago', 'b-confidencialidad', 'e-penalidad-retraso', 'b-propiedad-intelectual']],
['servicios', 'Contrato de Interpretación', 'Interpretación simultánea o consecutiva.', ['e-precio-servicios', 'e-forma-pago', 'b-confidencialidad']],
['servicios', 'Contrato de Servicios Médicos', 'Prestación de servicios de salud.', ['e-precio-servicios', 'b-confidencialidad', 't-proteccion-datos', 'b-relacion-independiente']],
['servicios', 'Contrato de Servicios Odontológicos', 'Tratamiento dental y plan de pagos.', ['e-precio-servicios', 'e-pago-cuotas', 'b-confidencialidad', 't-proteccion-datos']],
['servicios', 'Contrato de Servicios Veterinarios', 'Atención de animales.', ['e-precio-servicios', 'e-forma-pago', 'b-relacion-independiente']],
['servicios', 'Contrato de Servicios de Arquitectura', 'Diseño arquitectónico y planos.', [...BLOQUE.economico, 'b-propiedad-intelectual', 't-aceptacion-entregables', 'e-penalidad-retraso']],
['servicios', 'Contrato de Servicios de Ingeniería', 'Diseño y supervisión técnica.', [...BLOQUE.economico, 'b-propiedad-intelectual', 't-aceptacion-entregables']],
['servicios', 'Contrato de Servicios de Seguridad', 'Vigilancia y protección de instalaciones.', ['e-precio-servicios', 'e-forma-pago', 'b-relacion-independiente', 'g-renovacion-automatica']],
['servicios', 'Contrato de Servicios de Limpieza', 'Limpieza periódica de instalaciones.', ['e-precio-servicios', 'e-forma-pago', 'g-renovacion-automatica', 'b-relacion-independiente']],
['servicios', 'Contrato de Catering', 'Servicio de alimentos para un evento.', ['e-precio-servicios', 'e-pago-anticipado', 'e-penalidad-retraso', 'g-terminacion-mutuo-acuerdo']],
['servicios', 'Contrato de Organización de Eventos', 'Planificación y ejecución de un evento.', [...BLOQUE.economico, 'e-pago-anticipado', 'm-entregables-creativos', 'e-penalidad-retraso']],
['servicios', 'Contrato de Fotografía', 'Servicio fotográfico y cesión de imágenes.', ['e-precio-servicios', 'e-pago-anticipado', 'm-derechos-imagen', 'b-propiedad-intelectual', 'm-entregables-creativos']],
['servicios', 'Contrato de Video y Producción Audiovisual', 'Producción de piezas audiovisuales.', [...BLOQUE.economico, 'm-derechos-imagen', 'b-propiedad-intelectual', 'm-entregables-creativos']],
['servicios', 'Contrato de Servicios de Transporte de Personas', 'Traslado de pasajeros.', ['e-precio-servicios', 'e-forma-pago', 'b-relacion-independiente', 'g-seguro-bienes']],
['servicios', 'Contrato de Mensajería', 'Entrega de documentos y paquetes.', ['e-precio-servicios', 'c-entrega-bien', 'e-penalidad-retraso']],
['servicios', 'Contrato de Servicios de Recursos Humanos', 'Reclutamiento y gestión de personal.', [...BLOQUE.economico, 'b-confidencialidad', 't-proteccion-datos']],
['servicios', 'Contrato de Headhunting', 'Búsqueda y selección de ejecutivos.', ['e-precio-servicios', 'e-comision-porcentaje', 'b-confidencialidad', 'g-penalidad']],
['servicios', 'Contrato de Servicios de Diseño Gráfico', 'Diseño de piezas gráficas y marca.', ['e-precio-servicios', 'm-entregables-creativos', 'b-propiedad-intelectual', 't-aceptacion-entregables']],
['servicios', 'Contrato de Redacción de Contenidos', 'Creación de textos por encargo.', ['e-precio-servicios', 'm-entregables-creativos', 'b-propiedad-intelectual', 't-uso-inteligencia-artificial']],
['servicios', 'Contrato de Servicios de Mantenimiento Técnico', 'Mantenimiento de equipos e instalaciones.', ['e-precio-servicios', 't-nivel-servicio', 'g-renovacion-automatica']],
['servicios', 'Contrato de Peritaje', 'Dictamen técnico o valoración.', ['e-precio-servicios', 'b-confidencialidad', 't-aceptacion-entregables', 'b-relacion-independiente']],
['servicios', 'Propuesta de Servicios Profesionales', 'Oferta formal de servicios con alcance y precio.', ['e-precio-servicios', 'm-entregables-creativos', 'g-declaraciones-partes']],

/* ══════════ CONSTRUCCIÓN (20) ══════════ */
['construccion', 'Contrato de Construcción a Precio Alzado', 'Obra por un precio fijo global.', [...BLOQUE.obraBase, 'e-precio-servicios', 'e-penalidad-retraso', 'c-vicios-ocultos']],
['construccion', 'Contrato de Construcción por Administración', 'Obra facturada por costos más honorarios.', [...BLOQUE.obraBase, 'e-reembolso-gastos', 'e-comision-porcentaje']],
['construccion', 'Contrato de Remodelación', 'Reforma de un inmueble existente.', [...BLOQUE.obraBase, 'e-precio-servicios', 'o-alcance-obra']],
['construccion', 'Contrato de Subcontratación de Obra', 'Encargo parcial a un subcontratista.', [...BLOQUE.obraBase, 'b-relacion-independiente', 'e-penalidad-retraso']],
['construccion', 'Contrato de Supervisión de Obra', 'Dirección técnica y control de calidad.', ['e-precio-servicios', 'o-recepcion-obra', 'b-relacion-independiente', 't-aceptacion-entregables']],
['construccion', 'Contrato de Diseño y Construcción', 'Proyecto y ejecución bajo un mismo contrato.', [...BLOQUE.obraBase, 'b-propiedad-intelectual', 'e-precio-servicios']],
['construccion', 'Contrato de Instalación Eléctrica', 'Instalación y certificación eléctrica.', [...BLOQUE.obraBase, 'c-vicios-ocultos']],
['construccion', 'Contrato de Instalación Sanitaria', 'Instalación de sistemas hidráulicos y sanitarios.', [...BLOQUE.obraBase, 'c-vicios-ocultos']],
['construccion', 'Contrato de Instalación de Aire Acondicionado', 'Suministro e instalación de climatización.', ['c-entrega-bien', 'o-plazo-obra', 'c-vicios-ocultos', 't-soporte-tecnico']],
['construccion', 'Contrato de Impermeabilización', 'Tratamiento de techos y superficies.', [...BLOQUE.obraBase, 'c-vicios-ocultos']],
['construccion', 'Contrato de Pintura', 'Trabajos de pintura interior y exterior.', ['o-plazo-obra', 'o-materiales', 'e-precio-servicios', 'o-recepcion-obra']],
['construccion', 'Contrato de Carpintería', 'Fabricación e instalación de piezas de madera.', ['o-materiales', 'o-plazo-obra', 'c-entrega-bien', 'c-vicios-ocultos']],
['construccion', 'Contrato de Herrería', 'Trabajos metálicos por encargo.', ['o-materiales', 'o-plazo-obra', 'c-entrega-bien', 'c-vicios-ocultos']],
['construccion', 'Contrato de Movimiento de Tierra', 'Excavación y nivelación de terreno.', ['o-plazo-obra', 'e-precio-servicios', 'i-descripcion-inmueble', 'e-penalidad-retraso']],
['construccion', 'Contrato de Suministro de Materiales', 'Provisión de materiales de construcción.', ['c-entrega-bien', 'o-materiales', 'e-forma-pago', 'e-penalidad-retraso']],
['construccion', 'Acta de Inicio de Obra', 'Constancia del comienzo de los trabajos.', ['o-plazo-obra', 'g-declaraciones-partes']],
['construccion', 'Acta de Recepción Provisional', 'Entrega con observaciones pendientes.', ['o-recepcion-obra', 'e-retencion-garantia']],
['construccion', 'Acta de Recepción Definitiva', 'Entrega final y liberación de retenciones.', ['o-recepcion-obra', 'e-retencion-garantia', 'c-vicios-ocultos']],
['construccion', 'Orden de Cambio de Obra', 'Modificación del alcance o del precio de la obra.', ['g-modificaciones', 'e-precio-servicios', 'o-plazo-obra']],
['construccion', 'Contrato de Garantía de Obra', 'Cobertura de vicios posteriores a la entrega.', ['c-vicios-ocultos', 'e-retencion-garantia', 'o-recepcion-obra']],

/* ══════════ TECNOLOGÍA / SOFTWARE (20) ══════════ */
['tecnologia', 'Contrato de Desarrollo de Software', 'Desarrollo a medida con entregables por hitos.', [...BLOQUE.economico, 't-propiedad-codigo', 't-entrega-codigo-fuente', 't-aceptacion-entregables', 'b-confidencialidad']],
['tecnologia', 'Contrato de Licencia de Software', 'Autorización de uso de un programa.', ['t-licencia-uso', 'e-precio-servicios', 't-soporte-tecnico', 'b-propiedad-intelectual']],
['tecnologia', 'Contrato SaaS', 'Software como servicio con suscripción mensual.', ['t-licencia-uso', ...BLOQUE.tecnologiaBase, 't-disponibilidad', 't-portabilidad-datos', 'g-renovacion-automatica']],
['tecnologia', 'Contrato de Mantenimiento de Software', 'Corrección de errores y actualizaciones.', ['t-soporte-tecnico', 't-nivel-servicio', 'e-precio-servicios', 'g-renovacion-automatica']],
['tecnologia', 'Contrato de Soporte Técnico', 'Asistencia técnica con niveles de servicio.', ['t-soporte-tecnico', 't-nivel-servicio', 'e-forma-pago']],
['tecnologia', 'Contrato de Hosting', 'Alojamiento de aplicaciones y datos.', ['t-disponibilidad', 't-respaldos', 't-seguridad-informacion', 't-continuidad', 'e-precio-servicios']],
['tecnologia', 'Contrato de Servicios en la Nube', 'Infraestructura y servicios gestionados.', [...BLOQUE.tecnologiaBase, 't-disponibilidad', 't-continuidad', 't-portabilidad-datos']],
['tecnologia', 'Acuerdo de Tratamiento de Datos Personales', 'Encargo de tratamiento conforme a la Ley 172-13.', ['t-proteccion-datos', 't-seguridad-informacion', 't-portabilidad-datos', 'g-penalidad']],
['tecnologia', 'Contrato de Ciberseguridad', 'Servicios de protección y monitoreo.', ['t-seguridad-informacion', 't-nivel-servicio', 'b-confidencialidad', 't-continuidad']],
['tecnologia', 'Contrato de Auditoría de Seguridad', 'Evaluación de vulnerabilidades.', ['t-seguridad-informacion', 'b-confidencialidad', 't-aceptacion-entregables', 'e-precio-servicios']],
['tecnologia', 'Contrato de Desarrollo Web', 'Creación de sitio o aplicación web.', [...BLOQUE.economico, 't-propiedad-codigo', 't-aceptacion-entregables', 'm-entregables-creativos']],
['tecnologia', 'Contrato de Desarrollo de Aplicación Móvil', 'Aplicación para iOS y Android.', [...BLOQUE.economico, 't-propiedad-codigo', 't-entrega-codigo-fuente', 't-aceptacion-entregables']],
['tecnologia', 'Contrato de Integración de Sistemas', 'Conexión entre plataformas existentes.', [...BLOQUE.economico, 't-aceptacion-entregables', 't-soporte-tecnico', 'b-confidencialidad']],
['tecnologia', 'Contrato de Migración de Datos', 'Traslado de información entre sistemas.', ['t-proteccion-datos', 't-respaldos', 't-aceptacion-entregables', 'e-precio-servicios']],
['tecnologia', 'Contrato de Servicios de Inteligencia Artificial', 'Desarrollo o uso de modelos de IA.', ['t-uso-inteligencia-artificial', 't-proteccion-datos', 'b-propiedad-intelectual', ...BLOQUE.economico]],
['tecnologia', 'Contrato de Community Manager', 'Gestión de redes sociales.', ['e-precio-servicios', 'm-entregables-creativos', 'm-derechos-imagen', 'b-propiedad-intelectual']],
['tecnologia', 'Términos y Condiciones de Uso', 'Condiciones de uso de una plataforma digital.', ['t-licencia-uso', 't-proteccion-datos', 'g-modificaciones', 'g-ley-aplicable']],
['tecnologia', 'Política de Privacidad', 'Información sobre el tratamiento de datos.', ['t-proteccion-datos', 't-seguridad-informacion', 't-portabilidad-datos']],
['tecnologia', 'Contrato de Escrow de Código Fuente', 'Depósito del código ante un tercero.', ['t-entrega-codigo-fuente', 't-propiedad-codigo', 'e-deposito-general']],
['tecnologia', 'Contrato de Consultoría Tecnológica', 'Asesoría en arquitectura y transformación digital.', [...BLOQUE.economico, 'b-confidencialidad', 't-aceptacion-entregables', 'b-relacion-independiente']],

/* ══════════ MARKETING / CREATIVO (20) ══════════ */
['marketing', 'Contrato de Agencia de Marketing', 'Gestión integral de marketing de una marca.', [...BLOQUE.economico, 'm-entregables-creativos', 'b-propiedad-intelectual', 'g-renovacion-automatica']],
['marketing', 'Contrato de Campaña Publicitaria', 'Diseño y ejecución de una campaña puntual.', ['e-precio-servicios', 'e-pago-anticipado', 'm-entregables-creativos', 'b-propiedad-intelectual']],
['marketing', 'Contrato de Influencer', 'Colaboración con creador de contenido.', ['e-precio-servicios', 'm-derechos-imagen', 'm-entregables-creativos', 'b-exclusividad', 'b-confidencialidad']],
['marketing', 'Contrato de Embajador de Marca', 'Representación continuada de una marca.', ['m-derechos-imagen', 'b-exclusividad', 'e-forma-pago', 'b-no-competencia']],
['marketing', 'Contrato de Cesión de Derechos de Imagen', 'Autorización para usar imagen y voz.', ['m-derechos-imagen', 'b-territorio', 'e-precio-servicios']],
['marketing', 'Contrato de Diseño de Identidad de Marca', 'Creación de logotipo y manual de marca.', ['m-entregables-creativos', 'b-propiedad-intelectual', 'e-precio-servicios', 't-aceptacion-entregables']],
['marketing', 'Contrato de Producción Publicitaria', 'Producción de piezas para campaña.', ['m-entregables-creativos', 'm-derechos-imagen', 'e-pago-anticipado', 'b-propiedad-intelectual']],
['marketing', 'Contrato de Medios', 'Compra de espacios publicitarios.', ['e-precio-servicios', 'e-forma-pago', 'b-territorio', 'e-penalidad-retraso']],
['marketing', 'Contrato de Relaciones Públicas', 'Gestión de comunicación y reputación.', [...BLOQUE.economico, 'b-confidencialidad', 'g-renovacion-automatica']],
['marketing', 'Contrato de Email Marketing', 'Campañas de correo con base de datos.', ['e-precio-servicios', 't-proteccion-datos', 'm-entregables-creativos']],
['marketing', 'Contrato de SEO y Posicionamiento', 'Optimización para buscadores.', ['e-precio-servicios', 'g-renovacion-automatica', 't-aceptacion-entregables']],
['marketing', 'Contrato de Publicidad Digital', 'Gestión de campañas pagadas en línea.', ['e-precio-servicios', 'e-comision-porcentaje', 'm-entregables-creativos']],
['marketing', 'Contrato de Investigación de Mercado', 'Estudio de mercado y análisis.', ['e-precio-servicios', 'b-confidencialidad', 't-aceptacion-entregables', 'b-propiedad-intelectual']],
['marketing', 'Contrato de Licencia de Contenido', 'Autorización de uso de material creativo.', ['b-propiedad-intelectual', 'b-territorio', 'e-precio-servicios']],
['marketing', 'Contrato de Ilustración', 'Encargo de obra ilustrada.', ['m-entregables-creativos', 'b-propiedad-intelectual', 'e-pago-anticipado']],
['marketing', 'Contrato de Locución', 'Grabación de voz para producción.', ['m-derechos-imagen', 'e-precio-servicios', 'b-propiedad-intelectual']],
['marketing', 'Contrato de Modelaje', 'Participación de modelo en producción.', ['m-derechos-imagen', 'e-precio-servicios', 'b-territorio']],
['marketing', 'Contrato de Impresión', 'Producción de material impreso.', ['c-entrega-bien', 'e-precio-servicios', 'e-penalidad-retraso', 'o-materiales']],
['marketing', 'Contrato de Stand y Ferias', 'Participación en feria comercial.', ['g-objeto-uso-bien', 'e-precio-servicios', 'e-pago-anticipado', 'g-penalidad']],
['marketing', 'Acuerdo de Colaboración Creativa', 'Coautoría en un proyecto creativo.', ['b-propiedad-intelectual', 'm-entregables-creativos', 'b-relacion-independiente']],

/* ══════════ COMPRAVENTA / COMERCIO (15) ══════════ */
['comercio', 'Contrato de Compraventa de Bienes Muebles', 'Venta de bienes con entrega y garantía.', ['c-objeto-compraventa', 'c-entrega-bien', 'c-vicios-ocultos', 'e-forma-pago']],
['comercio', 'Contrato de Compraventa a Plazos', 'Venta con pago fraccionado.', ['c-objeto-compraventa', 'e-pago-cuotas', 'g-intereses-moratorios', 'p-garantia-prestamo']],
['comercio', 'Contrato de Compraventa con Reserva de Dominio', 'La propiedad se transfiere al pagar la última cuota.', ['c-objeto-compraventa', 'e-pago-cuotas', 'p-garantia-prestamo', 'c-entrega-bien']],
['comercio', 'Contrato de Compraventa Internacional', 'Operación de comercio exterior.', ['c-objeto-compraventa', 'c-entrega-bien', 'e-moneda-pago', 'g-arbitraje', 'g-fuerza-mayor']],
['comercio', 'Contrato de Permuta de Bienes', 'Intercambio de bienes muebles.', ['c-objeto-compraventa', 'c-entrega-bien', 'c-vicios-ocultos']],
['comercio', 'Contrato de Venta al Por Mayor', 'Suministro mayorista con descuentos.', ['c-objeto-compraventa', 'e-forma-pago', 'c-entrega-bien', 'e-penalidad-retraso']],
['comercio', 'Orden de Compra', 'Pedido formal de bienes o servicios.', ['c-objeto-compraventa', 'c-entrega-bien', 'e-forma-pago']],
['comercio', 'Factura Proforma', 'Cotización formal previa a la venta.', ['e-precio-servicios', 'e-impuestos-retenciones', 'c-entrega-bien']],
['comercio', 'Contrato de Garantía de Producto', 'Cobertura de defectos de fabricación.', ['c-vicios-ocultos', 't-soporte-tecnico', 'e-reembolso-gastos']],
['comercio', 'Política de Devoluciones', 'Condiciones para devolver un producto.', ['c-vicios-ocultos', 'e-reembolso-gastos', 'c-entrega-bien']],
['comercio', 'Contrato de Comisión Mercantil', 'Venta por cuenta de un tercero.', ['e-comision-porcentaje', 'b-representacion', 'b-relacion-independiente']],
['comercio', 'Contrato de Exportación', 'Venta de bienes al exterior.', ['c-objeto-compraventa', 'c-entrega-bien', 'e-moneda-pago', 'g-fuerza-mayor', 'g-arbitraje']],
['comercio', 'Contrato de Importación', 'Compra de bienes del exterior.', ['c-objeto-compraventa', 'c-entrega-bien', 'e-moneda-pago', 'e-impuestos-retenciones']],
['comercio', 'Contrato de Almacenaje', 'Depósito de mercancía en almacén.', ['e-deposito-general', 'e-precio-servicios', 'g-seguro-bienes', 'c-entrega-bien']],
['comercio', 'Recibo de Pago', 'Comprobante de un pago recibido.', ['e-forma-pago', 'g-declaraciones-partes']],

/* ══════════ VEHÍCULOS (10) ══════════ */
['vehiculos', 'Contrato de Compraventa de Vehículo', 'Venta de vehículo con traspaso ante la DGII.', ['v-descripcion-vehiculo', 'c-objeto-compraventa', 'v-traspaso-vehiculo', 'c-vicios-ocultos', 'e-forma-pago']],
['vehiculos', 'Contrato de Compraventa de Vehículo a Plazos', 'Venta de vehículo con pago fraccionado.', ['v-descripcion-vehiculo', 'e-pago-cuotas', 'p-garantia-prestamo', 'v-traspaso-vehiculo']],
['vehiculos', 'Contrato de Alquiler de Vehículo', 'Arrendamiento de vehículo por días o meses.', ['v-descripcion-vehiculo', 'e-precio-alquiler', 'e-deposito-general', 'g-seguro-bienes', 'g-devolucion-bien']],
['vehiculos', 'Contrato de Leasing de Vehículo', 'Arrendamiento financiero con opción de compra.', ['v-descripcion-vehiculo', 'e-pago-cuotas', 'v-traspaso-vehiculo', 'g-seguro-bienes']],
['vehiculos', 'Contrato de Consignación de Vehículo', 'Entrega para su venta por un tercero.', ['v-descripcion-vehiculo', 'e-comision-porcentaje', 'c-entrega-bien']],
['vehiculos', 'Acta de Entrega de Vehículo', 'Constancia del estado al entregar.', ['v-descripcion-vehiculo', 'c-entrega-bien']],
['vehiculos', 'Autorización de Conducción', 'Permiso para que un tercero conduzca el vehículo.', ['v-descripcion-vehiculo', 'b-representacion', 'g-declaraciones-partes']],
['vehiculos', 'Contrato de Taller Mecánico', 'Reparación y mantenimiento de vehículo.', ['v-descripcion-vehiculo', 'e-precio-servicios', 'c-vicios-ocultos', 'e-penalidad-retraso']],
['vehiculos', 'Contrato de Transporte de Carga', 'Traslado de mercancía por carretera.', ['e-precio-servicios', 'c-entrega-bien', 'g-seguro-bienes', 'e-penalidad-retraso']],
['vehiculos', 'Declaración de Venta de Vehículo', 'Declaración jurada de la venta realizada.', ['v-descripcion-vehiculo', 'g-declaraciones-partes', 'v-traspaso-vehiculo']],

/* ══════════ PRÉSTAMOS / FINANCIAMIENTO (15) ══════════ */
['financiamiento', 'Contrato de Préstamo Personal', 'Préstamo entre particulares con plan de pagos.', ['p-capital-prestamo', 'p-amortizacion', 'g-intereses-moratorios', 'p-garantia-prestamo']],
['financiamiento', 'Contrato de Préstamo con Garantía Hipotecaria', 'Préstamo respaldado por un inmueble.', ['p-capital-prestamo', 'p-amortizacion', 'p-garantia-prestamo', 'i-descripcion-inmueble', 'g-intereses-moratorios']],
['financiamiento', 'Contrato de Préstamo con Garantía Prendaria', 'Préstamo respaldado por bienes muebles.', ['p-capital-prestamo', 'p-amortizacion', 'p-garantia-prestamo', 'g-intereses-moratorios']],
['financiamiento', 'Pagaré', 'Promesa incondicional de pago.', ['p-capital-prestamo', 'g-intereses-moratorios', 'g-notificaciones']],
['financiamiento', 'Contrato de Línea de Crédito', 'Crédito disponible hasta un límite.', ['p-capital-prestamo', 'g-intereses-moratorios', 'p-garantia-prestamo', 'g-renovacion-automatica']],
['financiamiento', 'Contrato de Factoring', 'Cesión de facturas para obtener liquidez.', ['g-cesion-permitida', 'e-comision-porcentaje', 'g-notificaciones', 'g-declaraciones-partes']],
['financiamiento', 'Contrato de Inversión', 'Aportación de capital a un proyecto.', ['p-capital-prestamo', 'g-declaraciones-partes', 'b-confidencialidad', 'g-arbitraje']],
['financiamiento', 'Acuerdo de Reestructuración de Deuda', 'Nuevo plan de pagos de una deuda vencida.', ['p-amortizacion', 'g-intereses-moratorios', 'g-modificaciones', 'g-terminacion-mutuo-acuerdo']],
['financiamiento', 'Contrato de Aval', 'Garantía personal de una obligación.', ['p-garantia-prestamo', 'g-obligaciones-partes', 'g-penalidad']],
['financiamiento', 'Carta de Cancelación de Deuda', 'Constancia de que la deuda quedó saldada.', ['g-declaraciones-partes', 'g-terminacion-mutuo-acuerdo']],
['financiamiento', 'Contrato de Cesión de Derechos de Cobro', 'Traspaso del derecho a cobrar.', ['g-cesion-permitida', 'g-notificaciones', 'e-forma-pago']],
['financiamiento', 'Contrato de Arrendamiento Financiero', 'Leasing de bienes de capital.', ['e-pago-cuotas', 'c-entrega-bien', 'p-garantia-prestamo', 'g-seguro-bienes']],
['financiamiento', 'Contrato de Mutuo con Interés', 'Préstamo de dinero con interés pactado.', ['p-capital-prestamo', 'p-amortizacion', 'g-intereses-moratorios']],
['financiamiento', 'Plan de Pagos', 'Calendario de amortización acordado.', ['p-amortizacion', 'e-pago-cuotas', 'g-intereses-moratorios']],
['financiamiento', 'Contrato de Fideicomiso de Garantía', 'Bienes en fideicomiso como garantía.', ['p-garantia-prestamo', 'g-declaraciones-partes', 'g-obligaciones-partes']],
]
